# Generated by Django 4.2.3 on 2023-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=56)),
                ('credito', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
