# Generated by Django 4.2.3 on 2023-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_curso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='faltas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
