# Generated by Django 4.2.3 on 2023-07-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_curso_faltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fRestantes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
