# Generated by Django 4.2.3 on 2023-07-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_curso_frestantes_alter_curso_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='fRestantes',
            new_name='fRestante',
        ),
        migrations.AddField(
            model_name='curso',
            name='fTotal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
