# Generated by Django 4.0.3 on 2023-11-25 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='horas',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2)], verbose_name='horas'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='turma',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2)], verbose_name='turma'),
        ),
    ]
