# Generated by Django 4.0.3 on 2023-11-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_materias_materia_rename_turmas_turma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
