# Generated by Django 4.2.5 on 2023-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name', 'matricula'],
            },
        ),
    ]
